### PR TITLE
fix: handle stale-followups --days arg safely and clarify release artifact naming

### LINKED ISSUE #326: [review-followup] PR #268: Consider guarding `--days` without a value (e.g. missing `$2`) to avoid a sil...
Source PR: https://github.com/Keith-CY/carrier/pull/268
PR title: chore: add report-only stale review-followup issue detector

Auto-created from a non-blocking review suggestion marked with `NBS:`.

## Suggestion
- [ ] Consider guarding `--days` without a value (e.g. missing `$2`) to avoid a silent shift or empty threshold.

## Trace
- review-comment:Keith-CY

### LINKED ISSUE #327: [review-followup] PR #291: Consider linking “Releases” to the actual releases page or note the expected ...
Source PR: https://github.com/Keith-CY/carrier/pull/291
PR title: docs(readme): add OpenClaw install flow verification checklist

Auto-created from a non-blocking review suggestion marked with `NBS:`.

## Suggestion
- [ ] Consider linking “Releases” to the actual releases page or note the expected artifact naming to reduce checklist ambiguity.

## Trace
- review-comment:Keith-CY

### PR DESCRIPTION
**Pull request by Akane-CN**
## Summary
- guard `scripts/stale-followups.sh --days` so missing or invalid values fail fast with a clear error
- clarify release artifact naming and direct Releases link in the install flow verification checklist (EN + 中文)

## Validation
- `bash -n scripts/stale-followups.sh`

Closes #326
Closes #327

### CODE REVIEW

File: scripts/stale-followups.sh [hunk 1]
```diff
@@ -15,6 +15,16 @@ THRESHOLD_DAYS=7
 while [[ $# -gt 0 ]]; do
   case "$1" in
     --days)
+      if [[ $# -lt 2 ]] || [[ "$2" == --* ]]; then
+        echo "Error: --days requires a numeric value." >&2
+        echo "Usage: $0 [--days N]" >&2
+        exit 1
+      fi
+      if ! [[ "$2" =~ ^[0-9]+$ ]]; then
+        echo "Error: --days must be a non-negative integer." >&2
```
Comment (dev01lay2) [inline scripts/stale-followups.sh]: Nice guard — handles both missing value and non-numeric input cleanly. 👍

**Comment by Akane-CN** [comment]
Thanks for the review note. CI is now fully green on this PR:
- Daemon Lint ✅
- Daemon Tests ✅
- Gateway Check ✅
- WIP ✅

I also enabled auto-merge (squash), so it should merge automatically once branch protection requirements are satisfied.

**Comment by Akane-CN** [comment]
Rebased this branch on latest `main` and resolved the merge conflict in `scripts/stale-followups.sh`.

What I updated:
- kept `--days` argument validation strict (positive integer)
- preserved explicit usage/help output for invalid input cases

Force-pushed updated head: `69cd6b0`.
Auto-merge (squash) remains enabled.
