### PR TITLE
fix: batch follow-up issue hardening (CI, credentials, smoke docs)

### LINKED ISSUE #1272: docs: reconcile superseded plans with canonical architecture index
Automated hourly architecture audit detected superseded/diverged docs that require canonical linkage.

Repository: Keith-CY/carrier
Default branch: main

Findings:
- superseded/diverged docs: 4

Required actions:
1) Ensure each superseded/diverged doc has clear status + pointer to canonical sections.
2) Keep canonical architecture index aligned with implementation.
3) Remove ambiguity for contributors.

### LINKED ISSUE #1275: [review-followup] PR #1274: Consider making metadata discovery recursive in scripts/ci/pr-package-comment...
Source PR: https://github.com/Keith-CY/carrier/pull/1274
PR title: fix(release): preserve .zip extension for PR test package downloads

Auto-created from a non-blocking review suggestion marked with `NBS:`.

## Suggestion
- [ ] Consider making metadata discovery recursive in scripts/ci/pr-package-comment.cjs (like previous find -type f behavior) to avoid missing JSON files if artifact extraction ever yields nested directories.

## Trace
- review:Akane-CN

### LINKED ISSUE #1276: [review-followup] PR #1274: The `.zip` check is a nice safeguard. If other archive formats are ever neede...
Source PR: https://github.com/Keith-CY/carrier/pull/1274
PR title: fix(release): preserve .zip extension for PR test package downloads

Auto-created from a non-blocking review suggestion marked with `NBS:`.

## Suggestion
- [ ] The `.zip` check is a nice safeguard. If other archive formats are ever needed (e.g. `.tar.gz`), this will need updating — but hard-coding `.zip` is the right call for now given the current build matrix.

## Trace
- review-comment:dev01lay2

### LINKED ISSUE #1277: [review-followup] PR #1271: Consider explicitly fetching pull_request.head.sha before changed_modules() d...
Source PR: https://github.com/Keith-CY/carrier/pull/1271
PR title: ci: fix coverage report baseline and enforce 3% product regression gate

Auto-created from a non-blocking review suggestion marked with `NBS:`.

## Suggestion
- [ ] Consider explicitly fetching pull_request.head.sha before changed_modules() diff calc to avoid shallow-checkout edge cases where PR scope can fall back to 'all modules'.

## Trace
- review:Akane-CN

### LINKED ISSUE #1278: [review-followup] PR #1271: The `changed_modules()` function silently returns empty on `git diff` failure...
Source PR: https://github.com/Keith-CY/carrier/pull/1271
PR title: ci: fix coverage report baseline and enforce 3% product regression gate

Auto-created from a non-blocking review suggestion marked with `NBS:`.

## Suggestion
- [ ] The `changed_modules()` function silently returns empty on `git diff` failure, which falls back to showing all modules. Might be worth a debug log, but the fail-open behavior is reasonable for CI.

## Trace
- review-comment:dev01lay2

### LINKED ISSUE #1281: [review-followup] PR #1280: This PR combines multiple substantial areas (onboarding, transport/pairing, m...
Source PR: https://github.com/Keith-CY/carrier/pull/1280
PR title: feat: unify onboarding runtime and managed add-agent flows

Auto-created from a non-blocking review suggestion marked with `NBS:`.

## Suggestion
- [ ] This PR combines multiple substantial areas (onboarding, transport/pairing, managed-instance flows, base-agent runtime/LLM, and CLI bootstrap). For follow-up changes, consider splitting by domain to reduce regression blast radius and simplify future reviews.

## Trace
- review:Akane-CN

### LINKED ISSUE #1282: [review-followup] PR #1280: This file grew to ~2800 lines. Consider decomposing into sub-packages (e.g. `...
Source PR: https://github.com/Keith-CY/carrier/pull/1280
PR title: feat: unify onboarding runtime and managed add-agent flows

Auto-created from a non-blocking review suggestion marked with `NBS:`.

## Suggestion
- [ ] This file grew to ~2800 lines. Consider decomposing into sub-packages (e.g. `cmd/carrier/onboard`, `cmd/carrier/instance`, `cmd/carrier/bootstrap`) to improve navigability and reduce merge conflict surface.

## Trace
- review-comment:dev01lay2

### LINKED ISSUE #1283: [review-followup] PR #1280: The credential store logic (`loadProviderCredential`, `saveProviderCredential...
Source PR: https://github.com/Keith-CY/carrier/pull/1280
PR title: feat: unify onboarding runtime and managed add-agent flows

Auto-created from a non-blocking review suggestion marked with `NBS:`.

## Suggestion
- [ ] The credential store logic (`loadProviderCredential`, `saveProviderCredential`, `loadCredentialFromKeychain`, `loadCredentialFromFile`, `saveCredentialToFile`, etc.) is duplicated nearly verbatim across three locations:

## Trace
- review-comment:dev01lay2

### LINKED ISSUE #1284: [review-followup] PR #1280: `startBackgroundSubprocess` starts child processes but doesn't propagate `con...
Source PR: https://github.com/Keith-CY/carrier/pull/1280
PR title: feat: unify onboarding runtime and managed add-agent flows

Auto-created from a non-blocking review suggestion marked with `NBS:`.

## Suggestion
- [ ] `startBackgroundSubprocess` starts child processes but doesn't propagate `context.Context`. If the parent is killed mid-bootstrap, background daemon/gateway processes may become orphans with stale PID files. Consider using `cmd.SysProcAttr` with `Setpgid` or a context-based shutdown to clean up child processes on exit.

## Trace
- review-comment:dev01lay2

### LINKED ISSUE #1295: [review-followup] PR #1294: Given this spans transport + onboarding + operational UI paths, keep a short ...
Source PR: https://github.com/Keith-CY/carrier/pull/1294
PR title: feat: address issues #1285-#1292 in one batch

Auto-created from a non-blocking review suggestion marked with `NBS:`.

## Suggestion
- [ ] Given this spans transport + onboarding + operational UI paths, keep a short post-merge smoke pass for auto->polling fallback, settings transport hint rendering, and managed instance add/start/stop/uninstall flows.

## Trace
- review:Akane-CN

### LINKED ISSUE #1296: [review-followup] PR #1294: `RedactErrorMessage` is called here but not defined in this file. If it's a s...
Source PR: https://github.com/Keith-CY/carrier/pull/1294
PR title: feat: address issues #1285-#1292 in one batch

Auto-created from a non-blocking review suggestion marked with `NBS:`.

## Suggestion
- [ ] `RedactErrorMessage` is called here but not defined in this file. If it's a simple string-replace redactor, consider documenting what it redacts (tokens? paths?) so future maintainers know the security boundary.

## Trace
- review-comment:dev01lay2

### LINKED ISSUE #1297: [review-followup] PR #1294: `lookupPIDsBySocketInode` iterates all /proc entries and reads every fd symli...
Source PR: https://github.com/Keith-CY/carrier/pull/1294
PR title: feat: address issues #1285-#1292 in one batch

Auto-created from a non-blocking review suggestion marked with `NBS:`.

## Suggestion
- [ ] `lookupPIDsBySocketInode` iterates all /proc entries and reads every fd symlink — this can be slow on systems with many processes. For `carrier stop` this is fine, but if reused in a hot path later, consider reading `/proc/<pid>/net/tcp` instead for a single-pass approach.

## Trace
- review-comment:dev01lay2

### PR DESCRIPTION
**Pull request by Keith-CY**
## Summary
- make PR package metadata discovery recursive in `scripts/ci/pr-package-comment.cjs` and keep strict `.zip` validation explicit
- harden CI coverage diff handling by explicitly fetching PR head sha and logging diff failures in `changed_modules()`
- extract provider credential persistence into shared package `daemon/credentialstore` and reuse from CLI + gateway to remove duplicated logic
- harden background subprocess startup in CLI by cleaning up child processes when PID persistence fails
- document post-merge smoke checklist, redaction boundary, and decomposition guidance in canonical docs

## Issues
Closes #1272
Closes #1275
Closes #1276
Closes #1277
Closes #1278
Closes #1281
Closes #1282
Closes #1283
Closes #1284
Closes #1295
Closes #1296
Closes #1297

## Validation
- `go test ./... -count=1` (repo root)
- `go test ./credentialstore ./internal/... ./server -count=1` (from `daemon/`)
- `go test ./internal/gateway -count=1` (from `daemon/`)
- `node --test scripts/ci/pr-package-comment.test.cjs`

### CODE REVIEW

File: daemon/credentialstore/store.go [hunk 1]
```diff
@@ -0,0 +1,172 @@
+package credentialstore
```
Comment (dev01lay2) [inline daemon/credentialstore/store.go]: NBS: `configv2/config.go` still contains its own `loadCredential`/`loadCredentialFromKeychain`/`loadCredentialFromFile` implementations (simplified variants without error returns). Consider migrating those to use this shared package too for full deduplication.
